### ISSUE TITLE
Apply Design Patterns

### ISSUE THREAD

**Issue by IgorHalfeld** [carolinaknoll/pomodoro-timer#1]
Hello carolina!

I see your PR for  @GDGDuqueDeCaxias and how any good curious, I went to your github give an overview on projects o/

I saw on your website that you are learning javascript and I like to encourage women to enter this world, so I will help you to do that project with good concepts of language.

If you accept, the first thing we would do would be to remove the jQuery and apply design patterns.

So... what do you think about this insane proposal?

Igor

**Comment by carolinaknoll** [comment]
Hello, Igor! 

First of all, I would like to thank you for taking a look at my projects and reviewing my code! Yes, I've been learning about front-end development and I really like the idea of creating websites and web apps.

I agree with you! Removing jQuery will be a big step for me, but it will add more value to this project, along with applying design patterns. The color scheme also seemed like a nice idea in the past, but now I see that it looks a bit too colorful and ends up leaving out a bit of the purpose of a Pomodoro itself.

Thank you for proposing this challenge, I accept! \o

Carolina

**Comment by IgorHalfeld** [comment]
Fantastic!

I sent to you by email my phone number :D
