### ISSUE TITLE
timeForBreak not defined

### ISSUE THREAD

**Issue by oleteacher** [carolinaknoll/pomodoro-timer#2]
Nice project! Thinking of using for little classroom project.

I am getting the error below (in dev console):

`Uncaught ReferenceError: timeForBreak is not defined at timerLoop (pomodoro-clock.js:44)`

Have tried to understand and fix, but no success. Any ideas?

Thanks for sharing.

Susan

**Comment by carolinaknoll** [comment]
Hey there, thanks for your contribution! 😄 

I am sorry for not reviewing this issue sooner. I have made some changes to this project since the date you have created this issue, so this should not be happening again.

In any case, thank you for taking your time to contribute with this issue. 😄
